buttons_size: 32
additional_html: "<a class=\"a2a_button_facebook\"></a>\r\n<a class=\"a2a_button_twitter\"></a>\r\n<a class=\"a2a_button_google_plus\"></a>\r\n"
additional_css: ''
additional_js: ''
universal_button: none
custom_universal_button: ''
universal_button_placement: before
no_3p: false
entities:
  media: 1
  node: 0
  comment: 0
  block_content: 0
  contact_message: 0
  crop: 0
  file: 0
  mailchimp_campaign: 0
  profile: 0
  shortcut: 0
  taxonomy_term: 0
  uc_cart_item: 0
  uc_order_product: 0
  uc_order: 0
  uc_payment_receipt: 0
  user: 0
  webform_submission: 0
  menu_link_content: 0
_core:
  default_config_hash: 9YPlBuinIKLe5jVEf-aIhZvKFn77i18yD4CrNR0BbVQ
