features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://Acappella_Central_LARGE_KEY_smaller_0_0.png'
favicon:
  use_default: false
  path: 'public://Acappella_Central_RGB_KEY_0_0.jpg'
  mimetype: image/jpeg
