product_bundles:
  default: default
  recurring_product: recurring_product
negate_product_bundles: 0
redirection_route_path: cart
redirection_route_path_other: ''
add_to_cart_replacement_text: 'Add to cart'
