_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU
api_key: 57360e56beb539e2c5b93649b55bdf57-us4
api_timeout: 10
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
enable_connected: true
connected_id: null
connected_paths: null
webhook_hash: eb75ce9744c41cf9d374ab3055ecfbc4
optin_check_email_msg: 'Please check your email to confirm your subscription.'
