_core:
  default_config_hash: FWyW0pDoSvPRtqOVlIbk4PxTLiS9S_Ng7zS1JOflWVE
enable: true
address: test.ckln@gmail.com
roles:
  - authenticated
  - administrator
  - paid_member
allowed: ''
description: true
message: true
mailkeys: ''
mailkeys_skip: ''
